# ============================================
# Claude Code - Official Anthropic Configuration
# ============================================
# This file extends the base configuration with official Claude API settings
services:
  claude:
    extends:
      file: ../docker-compose.base.yml
      service: claude-base

    container_name: claude-default

    # Official Claude entrypoint
    entrypoint: /usr/local/bin/setup-default.sh

    # Volumes: claude data + workspace
    volumes:
      - ./claude-data:/home/claude/.claude
      - ${WORKSPACE_PATH:-../../beancount-LLM/Beancount-LLM}:/workspace

    # Official Anthropic environment variables
    environment:
      - HOME=/home/claude
      - CLAUDE_CONFIG_DIR=/home/claude/.claude
      - CLAUDE_SKIP_ONBOARDING=true
      - CLAUDE_CONFIG_FILE=/home/claude/.claude/settings.json
      - AUTO_UPDATE_CLAUDE=${AUTO_UPDATE_CLAUDE:-false}
      # Official Anthropic API key
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
